### ISSUE TITLE
Noisy yarn output

### ISSUE THREAD

**Issue by iHiD** [exercism/website#204]
I get this when running `yarn test`. Things still pass.

```js
  ● Console

    console.error
      Warning: Each child in a list should have a unique "key" prop.
      
      Check the render method of `List`. See https://fb.me/react-warning-keys for more information.
          in Track (at List.jsx:12)
          in List (at TracksList.jsx:58)
          in section (at TracksList.jsx:49)
          in div (at TracksList.jsx:42)
          in TracksList (at TracksList.test.js:45)

       8 | 
       9 |   return (
    > 10 |     <div className="tracks">
         |     ^
      11 |       {data.tracks.map((track) => {
      12 |         return <Track key={track.id} track={track} />
      13 |       })}

      at printWarning (node_modules/react/cjs/react.development.js:315:30)
      at error (node_modules/react/cjs/react.development.js:287:5)
      at validateExplicitKey (node_modules/react/cjs/react.development.js:1630:5)
      at validateChildKeys (node_modules/react/cjs/react.development.js:1656:9)
      at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:1806:7)
      at List (app/javascript/components/student/tracks-list/List.jsx:10:5)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14803:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:17482:13)

 PASS  test/javascript/components/mentoring/Inbox.test.js```

**Comment by SleeplessByte** [comment]
It's an out-of-band warning -- so whomever fixes this, don't fix it by "hiding" the log. Fix the actual warning.

**Comment by ErikSchierboom** [comment]
I suspect this will also pop-up when someone makes the effort of [fixing the linting warnings](https://github.com/exercism/v3-website/issues/200).

**Comment by SleeplessByte** [comment]
I doubt it. This is a react-internal warning you'll only see in devmode. I don't _think_ the react eslint currently doubly checks for it, but idk.

**Comment by ErikSchierboom** [comment]
Ah, it would have been nice :)
